Comport:
  port:              "/dev/ttyACM4" # `linux`: `/dev/ttyACMx` / `windows`: `COMx` (x: int)
  baudrate:          115200         # available baudrates are 300, 1200, 2400, 9600, 14400, 19200, 38400, 57600, 115200
  warmup:            2.0            # sec (should not be changed.)

Experimental:
  trial:             120            # Number of trials per session
  us-duration:       0.05           # Duration of US-presentation (sec)
  required-response: 10             # Number of responses required to obtain rewards
  lick:              10             # Arduino pin to detect lickings
  lever:             9              # Arduino pin to detect lever pressings
  us:                12             # Arduino pin to present US
  reward-signal:     True           # make a beep in the moment of reward
  speaker:           0              # speaker index to use
  cam-id:            0              # camera index
  video:             False          # whether record a video or not

Metadata:
  subject:           "enter-subject-name"
  condition:         "enter-experimental-condition"

PinMode:
  12:                "OUTPUT"
  10:                "SSINPUT_PULLUP"
  9:                 "SSINPUT_PULLUP"
